name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install needed packages
        run: |
          sudo apt install cmake clang-15 qt6-base-dev libglx-dev libgl1-mesa-dev libxkbcommon-dev -y

      - name: Build
        run: mkdir build && cd build && cmake .. && make -j$(nproc)


  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo HI!

  upload_release:
    runs-on: ubuntu-latest

    needs: [build_linux, build_windows]

    steps:
      - name: Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-nightly"
          prerelease: true
          title: "Nightly release"
          description: ""
          files: |
            build/DesktopZephyr
