name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install needed packages
        run: |
          sudo apt install cmake clang-15 qt6-base-dev libglx-dev libgl1-mesa-dev libxkbcommon-dev autoconf automake autopoint git clang-15 python3 python3-is-python ruby libtool-bin gperf lzip -y

      - name: Build
        run: mkdir build && cd build && cmake .. && make -j$(nproc)

      - name: Download MXE
        run: |
          git clone https://github.com/mxe/mxe.git --depth 1

      - name: Build MXE
        run: cd mxe && make qt

      - name: Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-nightly"
          prerelease: true
          title: "Nightly release"
          description: ""
          files: |
            build/DesktopZephyr
